package cis625project.messaging;

/**
 * @author platinix
 */
public enum MessageType {

  SUCCESS, ERROR, ACCESS_DENIED,
  ADD_MEDICAL_DEVICE,
  REMOVE_MEDICAL_DEVICE,
  GET_MEDICAL_DEVICES, GET_MEDICAL_DEVICES_REPLY,
  START_MEDICAL_DEVICE,
  MEDICAL_DEVICE_REPLY,
  STOP_MEDICAL_DEVICE,
  ADD_MEDICAL_RECORD,
  REMOVE_MEDICAL_RECORD,
  GET_MEDICAL_RECORD, GET_MEDICAL_RECORD_REPLY,
  GET_MEDICAL_RECORDS, GET_MEDICAL_RECORDS_REPLY
}
